#pragma once
#include"startCommand.h"
#include"GetLableNameCommand.h"
#include"SetLabelCommand.h"
#include"SaveCommand.h"
#include"LoadLeftLableCommand.h"
#include"LoadRightLableCommand.h"
#include"SetBoardCommand.h"
#include"GetSetting.h"
#include"ProgressCommand.h"
#include"UpdateRightLabel.h"
#include"ResetCommand.h"
#include"SetCommand.h"
#include"StartButtonEnable.h"
#include"QuitCommand.h"
#include"JudgeIsRunningCommand.h"